runtime: nodejs12

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  
  - url: /
    static_dir: build

endpoints_api_service:
  name: api-dot-concrete-zephyr-312801.uc.r.appspot.com
  rollout_strategy: managed